dependencies:
  - name: rabbitmq
    version: ^0.6.11
    repository: https://kubernetes-charts.storage.googleapis.com
  - name: nginx-ingress
    version: ^0.8.11
    repository: https://kubernetes-charts.storage.googleapis.com
  - name: volume_nfs
    version: ^0.1.0