replicaCount: 1
image:
  repository: quay.io/alfresco/alfresco-identity-service
  tag: latest
  pullPolicy: Always
service:
  name: alfresco-identity
  type: NodePort
  externalPort: 8180
  internalPort: 8180
ingress:
  path: /auth