# Default values for Alfresco Process Services.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

alfresco-process-services:
  enabled: true
  resources:
    requests:
      memory: "2000Mi"
    limits:
      memory: "3000Mi"
  nginx-ingress:
    enabled: false
  postgresql:
    persistence:
      enabled: false
alfresco-activiti-cloud-registry:
  enabled: true
  nginx-ingress:
    enabled: false
alfresco-activiti-cloud-gateway:
  enabled: true
alfresco-activiti-cloud-sso-idm:
  enabled: true

alfresco-content-services:
  enabled: true
  nginx-ingress:
    enabled: false
  repository:
    image:
      repository: quay.io/alfresco/alfresco-dbp-repository
      tag: "0.1-SNAPSHOT"
    environment:
      # The SYNC_SERVICE_URI should contain the details of the ingress host and port.
      SYNC_SERVICE_URI: "<ingresscontrollerurl>/syncservice"
      JAVA_OPTS: " -Dsolr.base.url=/solr
        -Dsolr.secureComms=none
        -Dindex.subsystem.name=solr6
        -Ddsync.service.uris=\"$SYNC_SERVICE_URI\"
        -Dmessaging.broker.url=\"failover:(tcp://${RELEASE_NAME}-alfresco-sync-service-activemq:61616)?timeout=3000\""
  share:
    image:
      repository: quay.io/alfresco/alfresco-dbp-share
      tag: "0.1-SNAPSHOT"
    resources:
      requests:
        memory: "1000Mi"
      limits:
        memory: "2000Mi"
  solr:
    resources:
      requests:
        memory: "500Mi"
      limits:
        memory: "1500Mi"

alfresco-sync-service:
  enabled: true
  postgresql:
    persistence:
      enabled: false
