replicaCount: 1
image:
  repository: activiti/activiti-cloud-gateway
  tag: latest
  pullPolicy: Always
service:
  name: activiti-cloud-gateway
  externalPort: 8080
  internalPort: 8080
  type: NodePort
ingress:
  path: /
  
eurekaURL:
keycloakURL:
rabbitmqReleaseName: