replicaCount: 1
registryPullSecrets: quay-registry-secret

syncservice:
  image:
    repository: quay.io/alfresco/service-sync
    tag: 2.2-SNAPSHOT
    pullPolicy: Always
    internalPort: 9090
  service:
    name: syncservice
    type: NodePort
    externalPort: 80
  ingress:
    path: /syncservice
  resources:
    requests:
      memory: "1000Mi"
    limits:
      memory: "2000Mi"

activemq:
  broker:
    host:
    ports:
      amqp: 5672
      openwire: 61616

repository:
  host:
  port:


persistence: 
  enabled: true
  baseSize: 10Gi
  efs:
    enabled: false
    dns: fs-example.efs.us-east-1.amazonaws.com
    path: "/"

database:
  persistence:
    size: 2Gi

postgresql:
  nameOverride: postgresql-syncservice
  persistence:
    existingClaim: "sync-services-pvc"
    subPath: "alfresco-sync-services/database-data"
  postgresUser: alfresco
  postgresPassword: admin
  postgresDatabase: syncservice-postgresql