apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "syncservice.fullname" . }}-activemq
  labels:
    app: {{ template "syncservice.fullname" . }}-activemq
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "syncservice.fullname" . }}
        release: {{ .Release.Name }}
    spec:
      initContainers:
      - name: init-repository
        image: busybox
        env:
        - name: REPOSITORY_HOST
          value: {{ .Values.syncservice.repository_host | default (printf "%s-alfresco-content-services-repository" .Release.Name) | quote }}
        - name: REPOSITORY_PORT
          value: {{ .Values.syncservice.repository_port | default 80 | quote }}
        command: ['sh', '-c', 'until $(wget -qO- -t 1 --timeout=1 http://$REPOSITORY_HOST:$REPOSITORY_PORT &> /dev/null); do echo "waiting for alfresco repo to start"; sleep 5; done;']
      containers:
      - name: activemq
        image: "{{ .Values.activemq.image.repository }}:{{ .Values.activemq.image.tag }}"
        imagePullPolicy: {{ .Values.activemq.image.pullPolicy }}
        env:
        - name: ACTIVEMQ_CONFIG_MINMEMORY
          value: "{{ .Values.activemq.image.configMinMemory }}"
        - name: ACTIVEMQ_CONFIG_MAXMEMORY
          value: "{{ .Values.activemq.image.configMaxMemory }}"
        ports:
        - name: listenport
          containerPort: 61616
        - name: monitoringport
          containerPort: 8161
        livenessProbe:
          httpGet:
            path: /
            port: 8161
          initialDelaySeconds: 5
          periodSeconds: 25
        resources:
{{ toYaml .Values.activemq.resources | indent 12 }}
