apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: syncservice
  annotations:
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/ssl-redirect: "false"
    ingress.kubernetes.io/rewrite-target: /alfresco
spec:
  rules:
  - http:
      paths:
      - path: /syncservice
        backend:
          serviceName: syncservice
          servicePort: 9090
