name: alfresco-dbp
version: 1.6.0-SNAPSHOT-DEPLOY-931
description: A Helm chart for the Alfresco Digital Business Platform
keywords:
- alfresco
- dbp
- platform
home: https://www.alfresco.com/platform
maintainers:
- name: Alfresco Platform Services Team
appVersion: 1.6-SNAPSHOT
