name: CI

on: [push,pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - name: Trigger Alfresco DBP Pipeline
      run: |
        BRANCH=${{ steps.extract_branch.outputs.branch }}
        CRUMB=$(curl -u builduser:${{ secrets.JenkinsToken }} 'http://jenkins-jx.jx-ps.dev.alfresco.me/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,":",//crumb)')
        curl -X POST -u builduser:${{ secrets.JenkinsToken }} -H "$CRUMB" 'http://jenkins-jx.jx-ps.dev.alfresco.me/job/platform-services/job/alfresco-dbp-test/job/DEPLOY-932/buildWithParameters?BRANCH_NAME=$BRANCH'
