apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "activiti-sso.fullname" . }}-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/ssl-redirect: "false"  
spec:
  rules:
  - http:
      paths:
      - path: {{ .Values.ingress.path }}
        backend:
          serviceName: {{ template "activiti-sso.fullname" . }}
          servicePort: {{ .Values.service.externalPort }}